name: Babelfish Smoke Tests
on: [push, pull_request]

jobs:
  isolation-tests:
    name: Isolation-Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        id: checkout

      - name: Install Dependencies
        id: install-dependencies
        if: always()
        uses: ./.github/composite-actions/install-dependencies

      - name: Build Modified Postgres
        id: build-modified-postgres
        if: always() && steps.install-dependencies.outcome == 'success'
        uses: ./.github/composite-actions/build-modified-postgres
      
      - name: Build Extensions
        id: build-extensions
        if: always() && steps.build-modified-postgres.outcome == 'success'
        uses: ./.github/composite-actions/build-extensions
      
      - name: Install Extensions
        id: install-extensions
        if: always() && steps.build-extensions.outcome == 'success'
        uses: ./.github/composite-actions/install-extensions

      - name: Enable SSL
        id: enable-ssl
        if: always() && steps.install-extensions.outcome == 'success'
        uses: ./.github/composite-actions/enable-ssl
      
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: Configure Python environment
        run: |
          cd ~
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          cd ~/work/babelfish_extensions/babelfish_extensions/test/python
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 python3-dev
          pip3 install pyodbc pymssql pytest pytest-xdist antlr4-python3-runtime==4.9.3
      
      - name: Generate .spec file parser
        run: |
          cd ~/work/babelfish_extensions/babelfish_extensions/test/python/isolationtest/
          java -Xmx500M -cp ../../../contrib/babelfishpg_tsql/antlr/thirdparty/antlr/antlr-4.9.3-complete.jar org.antlr.v4.Tool -Dlanguage=Python3 ./parser/*.g4 -visitor -no-listener

      - name: Run Isolation tests
        run: | 
          cd test/python
          compareWithFile=true \
            driver=pyodbc \
            runInParallel=false \
            testName=all \
            provider="ODBC Driver 18 for SQL Server" \
            fileGenerator_URL=localhost \
            fileGenerator_port=1433 \
            fileGenerator_databaseName=master \
            fileGenerator_user=jdbc_user \
            fileGenerator_password=12345678 \
            inputFilesPath=./input/isolation \
            runIsolationTests=true \
            stepTimeLimit=30 \
            pytest -s --tb=long -q .
