name: Windows JDBC Tests
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: clone-repository
      uses: actions/checkout@v4
    - name: build-and-test
      run: cmd /c ".github\scripts\windows-build.bat"
    - name: upload-testinfo
      uses: actions/upload-artifact@v4
      with:
        name: testinfo
        path: test/JDBC/Info
        retention-days: 1
    - name: upload-dist
      if: true
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist
        retention-days: 1
